# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_darsteller_suchen.ui'
#
# Created: Tue Mar 13 22:32:20 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DarstellerSuche(object):
    def setupUi(self, DarstellerSuche):
        DarstellerSuche.setObjectName("DarstellerSuche")
        DarstellerSuche.resize(867, 295)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pypordb/8027068_splash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DarstellerSuche.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(DarstellerSuche)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(DarstellerSuche)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditDarstellerSuche = QtGui.QLineEdit(self.groupBox)
        self.lineEditDarstellerSuche.setObjectName("lineEditDarstellerSuche")
        self.gridlayout.addWidget(self.lineEditDarstellerSuche, 0, 1, 1, 4)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBoxDarstellerSucheGeschlecht = QtGui.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheGeschlecht.setObjectName("comboBoxDarstellerSucheGeschlecht")
        self.comboBoxDarstellerSucheGeschlecht.addItem("")
        self.comboBoxDarstellerSucheGeschlecht.addItem("")
        self.gridlayout.addWidget(self.comboBoxDarstellerSucheGeschlecht, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(661, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 2, 1, 3)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dateEditDarstellerSucheAb = QtGui.QDateEdit(self.groupBox)
        self.dateEditDarstellerSucheAb.setMinimumDate(QtCore.QDate(1752, 9, 14))
        self.dateEditDarstellerSucheAb.setCalendarPopup(True)
        self.dateEditDarstellerSucheAb.setObjectName("dateEditDarstellerSucheAb")
        self.gridlayout.addWidget(self.dateEditDarstellerSucheAb, 2, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(611, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 2, 3, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.dateEditDarstellerSucheBis = QtGui.QDateEdit(self.groupBox)
        self.dateEditDarstellerSucheBis.setCalendarPopup(True)
        self.dateEditDarstellerSucheBis.setDate(QtCore.QDate(2000, 1, 1))
        self.dateEditDarstellerSucheBis.setObjectName("dateEditDarstellerSucheBis")
        self.gridlayout.addWidget(self.dateEditDarstellerSucheBis, 3, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(611, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 3, 3, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.comboBoxDarstellerSucheHaar = QtGui.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheHaar.setObjectName("comboBoxDarstellerSucheHaar")
        self.comboBoxDarstellerSucheHaar.addItem("")
        self.comboBoxDarstellerSucheHaar.setItemText(0, "")
        self.comboBoxDarstellerSucheHaar.addItem("")
        self.comboBoxDarstellerSucheHaar.addItem("")
        self.comboBoxDarstellerSucheHaar.addItem("")
        self.comboBoxDarstellerSucheHaar.addItem("")
        self.gridlayout.addWidget(self.comboBoxDarstellerSucheHaar, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(661, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem3, 4, 2, 1, 3)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBoxDarstellerSucheNation = QtGui.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheNation.setObjectName("comboBoxDarstellerSucheNation")
        self.gridlayout.addWidget(self.comboBoxDarstellerSucheNation, 5, 1, 1, 4)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.comboBoxDarstellerSucheTattoo = QtGui.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheTattoo.setObjectName("comboBoxDarstellerSucheTattoo")
        self.comboBoxDarstellerSucheTattoo.addItem("")
        self.comboBoxDarstellerSucheTattoo.setItemText(0, "")
        self.comboBoxDarstellerSucheTattoo.addItem("")
        self.comboBoxDarstellerSucheTattoo.addItem("")
        self.gridlayout.addWidget(self.comboBoxDarstellerSucheTattoo, 6, 1, 1, 1)
        self.lineEditDarstellerSucheTattoo = QtGui.QLineEdit(self.groupBox)
        self.lineEditDarstellerSucheTattoo.setObjectName("lineEditDarstellerSucheTattoo")
        self.gridlayout.addWidget(self.lineEditDarstellerSucheTattoo, 6, 2, 1, 3)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.comboBoxDarstellerSucheEthnic = QtGui.QComboBox(self.groupBox)
        self.comboBoxDarstellerSucheEthnic.setObjectName("comboBoxDarstellerSucheEthnic")
        self.comboBoxDarstellerSucheEthnic.addItem("")
        self.comboBoxDarstellerSucheEthnic.setItemText(0, "")
        self.comboBoxDarstellerSucheEthnic.addItem("")
        self.comboBoxDarstellerSucheEthnic.addItem("")
        self.comboBoxDarstellerSucheEthnic.addItem("")
        self.comboBoxDarstellerSucheEthnic.addItem("")
        self.gridlayout.addWidget(self.comboBoxDarstellerSucheEthnic, 7, 1, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(491, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 7, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButtonSuchen = QtGui.QPushButton(DarstellerSuche)
        self.pushButtonSuchen.setObjectName("pushButtonSuchen")
        self.hboxlayout.addWidget(self.pushButtonSuchen)
        self.pushButtonRefresh = QtGui.QPushButton(DarstellerSuche)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.hboxlayout.addWidget(self.pushButtonRefresh)
        self.pushButtonCancel = QtGui.QPushButton(DarstellerSuche)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.hboxlayout.addWidget(self.pushButtonCancel)
        self.verticalLayout_2.addLayout(self.hboxlayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(DarstellerSuche)
        QtCore.QMetaObject.connectSlotsByName(DarstellerSuche)
        DarstellerSuche.setTabOrder(self.lineEditDarstellerSuche, self.comboBoxDarstellerSucheNation)
        DarstellerSuche.setTabOrder(self.comboBoxDarstellerSucheNation, self.pushButtonSuchen)
        DarstellerSuche.setTabOrder(self.pushButtonSuchen, self.pushButtonRefresh)
        DarstellerSuche.setTabOrder(self.pushButtonRefresh, self.pushButtonCancel)

    def retranslateUi(self, DarstellerSuche):
        DarstellerSuche.setWindowTitle(QtGui.QApplication.translate("DarstellerSuche", "Search actor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DarstellerSuche", "Search criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DarstellerSuche", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DarstellerSuche", "Gender", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheGeschlecht.setItemText(0, QtGui.QApplication.translate("DarstellerSuche", "w", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheGeschlecht.setItemText(1, QtGui.QApplication.translate("DarstellerSuche", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DarstellerSuche", "Date from", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEditDarstellerSucheAb.setDisplayFormat(QtGui.QApplication.translate("DarstellerSuche", "dd.MM.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DarstellerSuche", "Date to", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEditDarstellerSucheBis.setDisplayFormat(QtGui.QApplication.translate("DarstellerSuche", "dd.MM.yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DarstellerSuche", "Hair color", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheHaar.setItemText(1, QtGui.QApplication.translate("DarstellerSuche", "bl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheHaar.setItemText(2, QtGui.QApplication.translate("DarstellerSuche", "br", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheHaar.setItemText(3, QtGui.QApplication.translate("DarstellerSuche", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheHaar.setItemText(4, QtGui.QApplication.translate("DarstellerSuche", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DarstellerSuche", "Nation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DarstellerSuche", "Tattoo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheTattoo.setItemText(1, QtGui.QApplication.translate("DarstellerSuche", "yes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheTattoo.setItemText(2, QtGui.QApplication.translate("DarstellerSuche", "no", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DarstellerSuche", "Ethnic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheEthnic.setItemText(1, QtGui.QApplication.translate("DarstellerSuche", "w", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheEthnic.setItemText(2, QtGui.QApplication.translate("DarstellerSuche", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheEthnic.setItemText(3, QtGui.QApplication.translate("DarstellerSuche", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxDarstellerSucheEthnic.setItemText(4, QtGui.QApplication.translate("DarstellerSuche", "l", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setText(QtGui.QApplication.translate("DarstellerSuche", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setShortcut(QtGui.QApplication.translate("DarstellerSuche", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setText(QtGui.QApplication.translate("DarstellerSuche", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("DarstellerSuche", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

