# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pordb_suchen.ui'
#
# Created: Sat May  4 23:31:14 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ErweiterteSuche(object):
    def setupUi(self, ErweiterteSuche):
        ErweiterteSuche.setObjectName(_fromUtf8("ErweiterteSuche"))
        ErweiterteSuche.resize(832, 291)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pypordb/8027068_splash.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ErweiterteSuche.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(ErweiterteSuche)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(ErweiterteSuche)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditDarsteller = QtGui.QLineEdit(self.groupBox)
        self.lineEditDarsteller.setObjectName(_fromUtf8("lineEditDarsteller"))
        self.gridLayout.addWidget(self.lineEditDarsteller, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditCD = QtGui.QLineEdit(self.groupBox)
        self.lineEditCD.setObjectName(_fromUtf8("lineEditCD"))
        self.gridLayout.addWidget(self.lineEditCD, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditTitel = QtGui.QLineEdit(self.groupBox)
        self.lineEditTitel.setObjectName(_fromUtf8("lineEditTitel"))
        self.gridLayout.addWidget(self.lineEditTitel, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditOriginal = QtGui.QLineEdit(self.groupBox)
        self.lineEditOriginal.setObjectName(_fromUtf8("lineEditOriginal"))
        self.gridLayout.addWidget(self.lineEditOriginal, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBoxVid = QtGui.QCheckBox(self.groupBox)
        self.checkBoxVid.setToolTip(_fromUtf8(""))
        self.checkBoxVid.setText(_fromUtf8(""))
        self.checkBoxVid.setObjectName(_fromUtf8("checkBoxVid"))
        self.gridLayout.addWidget(self.checkBoxVid, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboBoxCS = QtGui.QComboBox(self.groupBox)
        self.comboBoxCS.setMaximumSize(QtCore.QSize(723, 16777215))
        self.comboBoxCS.setObjectName(_fromUtf8("comboBoxCS"))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.setItemText(0, _fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.comboBoxCS.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxCS, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.pushButtonSuchen = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonSuchen.setToolTip(_fromUtf8(""))
        self.pushButtonSuchen.setObjectName(_fromUtf8("pushButtonSuchen"))
        self.hboxlayout.addWidget(self.pushButtonSuchen)
        self.pushButtonRefresh = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonRefresh.setToolTip(_fromUtf8(""))
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.hboxlayout.addWidget(self.pushButtonRefresh)
        self.pushButtonCancel = QtGui.QPushButton(ErweiterteSuche)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.hboxlayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.hboxlayout)

        self.retranslateUi(ErweiterteSuche)
        QtCore.QMetaObject.connectSlotsByName(ErweiterteSuche)
        ErweiterteSuche.setTabOrder(self.lineEditDarsteller, self.lineEditCD)
        ErweiterteSuche.setTabOrder(self.lineEditCD, self.lineEditTitel)
        ErweiterteSuche.setTabOrder(self.lineEditTitel, self.lineEditOriginal)
        ErweiterteSuche.setTabOrder(self.lineEditOriginal, self.checkBoxVid)
        ErweiterteSuche.setTabOrder(self.checkBoxVid, self.comboBoxCS)
        ErweiterteSuche.setTabOrder(self.comboBoxCS, self.pushButtonSuchen)
        ErweiterteSuche.setTabOrder(self.pushButtonSuchen, self.pushButtonRefresh)
        ErweiterteSuche.setTabOrder(self.pushButtonRefresh, self.pushButtonCancel)

    def retranslateUi(self, ErweiterteSuche):
        ErweiterteSuche.setWindowTitle(QtGui.QApplication.translate("ErweiterteSuche", "Extended search", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ErweiterteSuche", "Search criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ErweiterteSuche", "Actor", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditDarsteller.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Search for actors</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ErweiterteSuche", "CD", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditCD.setToolTip(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditCD.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Search for data storage medium</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ErweiterteSuche", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTitel.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Search for title</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ErweiterteSuche", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOriginal.setToolTip(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOriginal.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Search for original title</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ErweiterteSuche", "Video present", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxVid.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Filter search results only for videos which are present</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ErweiterteSuche", "CS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Filter search results with cumshots</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(1, QtGui.QApplication.translate("ErweiterteSuche", "f Facial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(2, QtGui.QApplication.translate("ErweiterteSuche", "h Handjob", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(3, QtGui.QApplication.translate("ErweiterteSuche", "t Tits", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(4, QtGui.QApplication.translate("ErweiterteSuche", "c Creampie", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(5, QtGui.QApplication.translate("ErweiterteSuche", "x Analcreampie", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(6, QtGui.QApplication.translate("ErweiterteSuche", "o Oralcreampie", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(7, QtGui.QApplication.translate("ErweiterteSuche", "v Cunt", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(8, QtGui.QApplication.translate("ErweiterteSuche", "b Belly", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(9, QtGui.QApplication.translate("ErweiterteSuche", "a Ass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(10, QtGui.QApplication.translate("ErweiterteSuche", "s Others", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxCS.setItemText(11, QtGui.QApplication.translate("ErweiterteSuche", "k No", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "Start search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setText(QtGui.QApplication.translate("ErweiterteSuche", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSuchen.setShortcut(QtGui.QApplication.translate("ErweiterteSuche", "Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "Clear all fields in search form", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRefresh.setText(QtGui.QApplication.translate("ErweiterteSuche", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setWhatsThis(QtGui.QApplication.translate("ErweiterteSuche", "<html><head/><body><p>Cancel search</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("ErweiterteSuche", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

